### ISSUE TITLE
Directive ignoring global options

### ISSUE THREAD

**Issue by kevinmelo** [dm4t2/vue-currency-input#133] opened 2020-06-26 11:27 UTC
I declare global options like `Vue.use(VueCurrencyInput, {autodecimalMode: true, precision: 2, distractionFree: false})` then in my input i used like this `<input v-currency />`  before i update to the last `vue-currency-input`.

But now he throws an error `Cannot read property 'valueAsInteger' of undefined`. Checking the code is when he try get options direct from directive.

To work, with `globalOptions` i have to put an empty object like  this `<input v-currency="{}" />`

Don't know if this is a bug or it's intensional now

**Comment by dm4t2** [comment] 2020-06-26 20:02
Hi, it looks like you've forgotten the `globalOptions` object when passing the plugin options:
https://codesandbox.io/s/vue-currency-input-133-2mo9i?file=/src/main.js

see also: https://dm4t2.github.io/vue-currency-input/config/#plugin-options

**Comment by kevinmelo** [comment] 2020-06-29 11:08
I'm declaring globalOptions like you said... But in my case still getting error

I will try to figure out what could be

**Comment by ascott18** [comment] 2020-07-08 16:45
@dm4t2 You can easily reproduce this by initializing the input with a value: https://codesandbox.io/s/vue-currency-input-133-td2qd

![image](https://user-images.githubusercontent.com/5017521/86946773-b9864780-c0ff-11ea-99ad-2b1c954c3d71.png)

**Comment by dm4t2** [comment] 2020-07-10 20:26
@ascott18: Thanks for reproducing the issue! I will fix this shortly 🚀

**Comment by dm4t2** [comment] 2020-07-10 21:24
Fixed in [Release 1.20.1](https://github.com/dm4t2/vue-currency-input/releases/tag/1.20.1) 🎉

I also updated my CodeSandbox: https://codesandbox.io/s/vue-currency-input-133-2mo9i

**Closed by dm4t2** 2020-07-10 21:24 UTC
Labels: bug
