### ISSUE TITLE
input not clear if use value.prop instead of v-model

### ISSUE THREAD

**Issue by mkosmen** [dm4t2/vue-currency-input#114] opened 2020-05-12 08:50 UTC
Hi guys,

i have a problem about clearing input so i use this plugin in vue file as component. it works normally when we change input but if i reset model value with a button, input not clearing. 

this is my filter components section
![Code_TETMVKvxDm](https://user-images.githubusercontent.com/3495912/81662320-1342fc00-9446-11ea-9f01-3ee10288786d.png)

filter clear button reset form[item.model].value but input not clearing ...

this is filter input component
![Code_C1WXB21JFC](https://user-images.githubusercontent.com/3495912/81662402-2d7cda00-9446-11ea-9528-af9f969dc050.png)

i use value.prop instead of v-model so on filter clear button pressed input not clearing. Why ? other 3rd plugins working with value.prop but this is not working.

How can i clear input ?

methods
![Code_hc5Km3Bw0L](https://user-images.githubusercontent.com/3495912/81662668-949a8e80-9446-11ea-8dda-30e7e0484a68.png)

**Comment by dm4t2** [comment] 2020-05-12 20:49
Can you explain why you are using the `prop` modifier? This would mutate the `value` DOM property on the `<currency-input>` component's `$el` directly causing unexpected behaviour, since the state of DOM property (the actual visible formatted value) needs be handled internally. 

You can reproduce this if you the set `distraction-free` option to `false`. 
If you remove the `prop` modifier it should work as expected.

**Comment by mkosmen** [comment] 2020-05-12 21:05
if i use v-model or value without prop modifier input not changing and on first image i use a form object which has all values for components. How can i use multiple v-model sametime for same component. If i remove prop modifier other components not working.

**Comment by dm4t2** [comment] 2020-05-12 21:20
This problem needs to be addressed by your application/component.

**Closed by dm4t2** 2020-05-12 21:20 UTC
