### ISSUE TITLE
disallow entering non-numeric characters in the field

### ISSUE THREAD

**Issue by stalker3343** [dm4t2/vue-currency-input#175] opened 2020-10-21 20:38 UTC
disallow entering non-numeric characters in the field

**Comment by titou10titou10** [comment] 2020-12-04 14:33
Any reason this has been closed? it would be great if non digit characters would be rejected and not displayed when typing

**Comment by dm4t2** [comment] 2020-12-04 20:59
It should not be possible to enter non-digits by default. You can verify this in the [playground](https://dm4t2.github.io/vue-currency-input/playground/). The issue was closed because no further information for reproducing was provided.

**Comment by stalker3343** [comment] 2020-12-05 09:29
![изображение](https://user-images.githubusercontent.com/42894422/101239020-6d165680-36f5-11eb-81a2-fe06f8ba5480.png)

**Comment by dm4t2** [comment] 2020-12-05 10:54
It works fine for me in the latest Chrome@Windows 10. Please provide more information about your environment (OS, Browser, Console error logs).

**Comment by titou10titou10** [comment] 2020-12-05 13:14
@dm4t2, my own tests:

- fail: firefox v83.0 / WIndows 10
- fail: firefox v83.0 / Windows 7
- fail: firefox v83.0 / Ubuntu 20.04.1 LTS
- OK: microsoft edge:v 87.0.664.52 / Windows 10
- OK chrome v87.0.4280.88 / Windows 7

**Comment by dm4t2** [comment] 2020-12-06 21:08
It's kind of strange... the problem seems only to occur with Firefox when using `v-currency` on Vuetify's `<v-text-field>` component. 

Other examples work: https://codesandbox.io/s/vue-currency-input-direct-browser-usage-yjtci

I need to look into this more closely.

**Comment by dm4t2** [comment] 2020-12-26 22:56
Fixed in [Release 2.0.0-beta.1](https://github.com/dm4t2/vue-currency-input/releases/tag/2.0.0-beta.1) 🎉

**Closed by dm4t2** 2020-12-26 22:56 UTC
Labels: bug
