### ISSUE TITLE
Cannot input Number.MAX_SAFE_INTEGER

### ISSUE THREAD

**Issue by TranManhThang96** [dm4t2/vue-currency-input#344] opened 2022-09-21 10:17 UTC
### Vue Currency Input version

2.1.0

### Vue version

3.0.0

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### Reproduction link

https://dm4t2.github.io/vue-currency-input/playground.html

### Describe your issue

<img width="740" alt="image" src="https://user-images.githubusercontent.com/32483289/191478415-20a0c37a-1c96-4804-ae59-7d0bc8119c06.png">

When I set precision: {min: 0, max:5}, the red space can't be entered anymore, but 5 digits after the decimal can still be entered. I want this place to be flexible to min, max.
Example
When set precision: {min: 0, max:5} can still enter 9,007,199,254,740,991
When set precision: {min: 1, max:5} can still enter 900,719,925,474,099.1

**Comment by dm4t2** [comment] 2022-10-02 19:39
This is actually a technical limitation, not a bug. The concatenated parts of integer + (max) fraction must be < Number.MAX_SAFE_INTEGER.

This will be addressed in #346.

**Closed by dm4t2** 2022-10-02 19:39 UTC
