### ISSUE TITLE
Export function that creates a currency string

### ISSUE THREAD

**Issue by VanishMax** [dm4t2/vue-currency-input#85] opened 2020-01-28 07:00 UTC
It would be great to let developers create their own manual currency behaviour with the function that creates a currency string and is opposite to `parseCurrency` function.

I saw you're using `Intl.NumberFormat()`, so, giving it some parameters listed in configuration, the use-case of the library will grow up.

**Comment by dm4t2** [comment] 2020-01-28 21:08
Seems to be a duplicate of #82. 
This won't solve #77, since there needs a lot more to be done than just exporting a "format" method.

**Closed by dm4t2** 2020-01-28 21:08 UTC
